### ISSUE TITLE
对go-jeans易用性方面的疑问与想法

### ISSUE THREAD

**Issue by TremblingV5** [Li-giegie/go-jeans#1]
我阅读了仓库里的代码，我感觉应该是只能通过`Encode(arg1, arg2, arg3, ...., argn)`这样的方式调用。这样的话可能就存在一个问题，我要传输的某个数据结构较为复杂，有比较多的字段，这样写起来就很麻烦，很容易出错，这对我来说是比较难接受的。相应的，可能得像protobuf那样去搞代码生成，来避免这样的困扰。

另外，创建一个结构体再使用结构体的字段去赋值可能显得“多次一举”，这么说的原因是编、解码看起来和结构体并没有关系，使用其他基本类型也是一样的。

在阅读源码的过程中，我认为go-jeans可能更应该表述为一个“二进制协议”库，而非序列化和反序列化的工具库。go-jeans的主要工作是通过传入参数，并转化为固定格式的二进制串，相应来说性能一定是不错的，与json和protobuf等协议相比性能一定是会更好的。但相应来说，也缺失了json或是protobuf协议所拥有的一些优点，例如json所拥有的易读性、易用性、扩展性，protobuf所拥有的强类型特性等。

**Comment by Li-giegie** [comment]
感谢你阅读我的开源项目并提出了这些问题。

我理解你对通过多次调用Encode(arg1, arg2, arg3, ...., argn)的方式感到不便和易错，尤其是当你需要传输复杂的数据结构时。你提到了像protobuf那样使用代码生成来避免这个问题，我认为这是一个好的建议，如果使用代码生成的话，会有两种选择
一：”直接生成手动编解码代码性能会进一步的提升，那么go-jeans应该是成为了一个工具，这个似乎不太符合go-jeans的定位，
二：生成一些辅助性的代码，例如Encode(arg1, arg2, arg3, ...., argn)，其中的args交给代码生成工具来完成，我想这个可能更符合。

你还提到，在阅读源码的过程中，你认为我的项目更适合被描述为一个“二进制协议”库，而不是一个序列化和反序列化工具库。你认为性能方面表现不错，并且比json和protobuf等协议更高效。然而，你也指出了与这些协议相比，我的项目缺少了一些优点，比如易读性、易用性和扩展性（对于json）以及强类型特性（对于protobuf）。目前而言我确实对一些概念定义出现了不准确，这个在后续的更改中会持续跟进。

我真诚地感谢你对我的项目的认真研究和宝贵建议。你的反馈对于改进我的项目来说非常重要。我会考虑如何更好地平衡性能和易用性，并尽量提供更多的扩展性。确保项目更好地满足用户的需求。如果你有其他建议或想法，请随时告诉我。非常感谢！
